# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
services:
    #parameter_name: value
    user_provider:
        class: Biz\User\UserProvider
        arguments:    ['@service_container']
security:
    encoders:
        Biz\Entity\User:
            algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
            webservice:
                id: user_provider
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # secured_area:
        #     form_login:
        #         csrf_token_generator: security.csrf.token_manager
        main:  
            pattern: /.*  
            form_login:  
            form_login:
                login_path: login
                check_path: login_check 
                default_target_path: /index
            logout:   
                path: /logout  
                target: /  
            security: true  
            anonymous: true
            http_basic: ~
            
    access_control:  
        - { path: /login, role: IS_AUTHENTICATED_ANONYMOUSLY }  
        - { path: /index/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }