login:
    path:  /login
    defaults: { _controller: AppBundle:Login/Login:index }

index:
    path:  /index
    defaults: { _controller: AppBundle:Default:index }

login_check:
    path:  /login_check

logout:
    path:  /logout

register: 
    path:  /register
    defaults: { _controller: AppBundle:Register/Register:register }