web_index:
    path:  /
    defaults: { _controller: AppBundle:Default:index }

login:
    path:  /login
    defaults: { _controller: AppBundle:Login:index }

index:
    path:  /index
    defaults: { _controller: AppBundle:Default:index }

login_check:
    path:  /login_check

logout:
    path:  /logout

register: 
    path:  /register
    defaults: { _controller: AppBundle:Register:register }

search:
    path: /search
    defaults: { _controller: AppBundle:Default:index }

article_default:
    path: /article/{id}
    defaults: { _controller: AppBundle:Article:detail }
    requirements:
        id: \d+

article_create:
    path: /article/create
    defaults: { _controller: AppBundle:Article:create }

